In [16]:
import yfinance as yf

sp = yf.download("^GSPC", start="2000-01-01", end="2023-12-31")
sp = sp["Adj Close"]

df_sp = sp.to_frame()
df_sp.to_csv("./data/sp500.csv")
df_sp

[*********************100%%**********************]  1 of 1 completed

              Adj Close
Date
2000-01-03  1455.219971
2000-01-04  1399.420044
2000-01-05  1402.109985
2000-01-06  1403.449951
2000-01-07  1441.469971
...                 ...
2023-12-22  4754.629883
2023-12-26  4774.750000
2023-12-27  4781.580078
2023-12-28  4783.350098
2023-12-29  4769.830078

[6037 rows x 1 columns]

In [17]:
### get stocks from s&p500
import requests
from bs4 import BeautifulSoup
import pandas as pd

# URL for the Wikipedia page that lists Dow Jones companies
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'

# Send a GET request to fetch the page content
response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Locate the table containing the Dow Jones components
table = soup.find('table', {'class': 'wikitable'})

# Parse the table into a pandas DataFrame
df = pd.read_html(str(table))[0]

# Print the DataFrame
print(df[['Symbol', 'Security']])

    Symbol             Security
0      MMM                   3M
1      AOS          A. O. Smith
2      ABT  Abbott Laboratories
3     ABBV               AbbVie
4      ACN            Accenture
..     ...                  ...
498    XYL           Xylem Inc.
499    YUM          Yum! Brands
500   ZBRA   Zebra Technologies
501    ZBH        Zimmer Biomet
502    ZTS               Zoetis

[503 rows x 2 columns]

/var/folders/xh/n_j2f34x3gbbkjmhhfy63yc00000gn/T/ipykernel_25865/3227050349.py:17: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_html(str(table))[0]

In [18]:
### get stocks symbols
symbols = df['Symbol'].tolist()
symbols

['MMM',
 'AOS',
 'ABT',
 'ABBV',
 'ACN',
 'ADBE',
 'AMD',
 'AES',
 'AFL',
 'A',
 'APD',
 'ABNB',
 'AKAM',
 'ALB',
 'ARE',
 'ALGN',
 'ALLE',
 'LNT',
 'ALL',
 'GOOGL',
 'GOOG',
 'MO',
 'AMZN',
 'AMCR',
 'AEE',
 'AAL',
 'AEP',
 'AXP',
 'AIG',
 'AMT',
 'AWK',
 'AMP',
 'AME',
 'AMGN',
 'APH',
 'ADI',
 'ANSS',
 'AON',
 'APA',
 'AAPL',
 'AMAT',
 'APTV',
 'ACGL',
 'ADM',
 'ANET',
 'AJG',
 'AIZ',
 'T',
 'ATO',
 'ADSK',
 'ADP',
 'AZO',
 'AVB',
 'AVY',
 'AXON',
 'BKR',
 'BALL',
 'BAC',
 'BK',
 'BBWI',
 'BAX',
 'BDX',
 'BRK.B',
 'BBY',
 'BIO',
 'TECH',
 'BIIB',
 'BLK',
 'BX',
 'BA',
 'BKNG',
 'BWA',
 'BSX',
 'BMY',
 'AVGO',
 'BR',
 'BRO',
 'BF.B',
 'BLDR',
 'BG',
 'BXP',
 'CDNS',
 'CZR',
 'CPT',
 'CPB',
 'COF',
 'CAH',
 'KMX',
 'CCL',
 'CARR',
 'CTLT',
 'CAT',
 'CBOE',
 'CBRE',
 'CDW',
 'CE',
 'COR',
 'CNC',
 'CNP',
 'CF',
 'CHRW',
 'CRL',
 'SCHW',
 'CHTR',
 'CVX',
 'CMG',
 'CB',
 'CHD',
 'CI',
 'CINF',
 'CTAS',
 'CSCO',
 'C',
 'CFG',
 'CLX',
 'CME',
 'CMS',
 'KO',
 'CTSH',
 'CL',
 'CMCSA',
 'CAG',
 'COP',
 'ED',
 'STZ',
 'CEG',
 'COO',
 'CPRT',
 'GLW',
 'CPAY',
 'CTVA',
 'CSGP',
 'COST',
 'CTRA',
 'CRWD',
 'CCI',
 'CSX',
 'CMI',
 'CVS',
 'DHR',
 'DRI',
 'DVA',
 'DAY',
 'DECK',
 'DE',
 'DAL',
 'DVN',
 'DXCM',
 'FANG',
 'DLR',
 'DFS',
 'DG',
 'DLTR',
 'D',
 'DPZ',
 'DOV',
 'DOW',
 'DHI',
 'DTE',
 'DUK',
 'DD',
 'EMN',
 'ETN',
 'EBAY',
 'ECL',
 'EIX',
 'EW',
 'EA',
 'ELV',
 'EMR',
 'ENPH',
 'ETR',
 'EOG',
 'EPAM',
 'EQT',
 'EFX',
 'EQIX',
 'EQR',
 'ESS',
 'EL',
 'ETSY',
 'EG',
 'EVRG',
 'ES',
 'EXC',
 'EXPE',
 'EXPD',
 'EXR',
 'XOM',
 'FFIV',
 'FDS',
 'FICO',
 'FAST',
 'FRT',
 'FDX',
 'FIS',
 'FITB',
 'FSLR',
 'FE',
 'FI',
 'FMC',
 'F',
 'FTNT',
 'FTV',
 'FOXA',
 'FOX',
 'BEN',
 'FCX',
 'GRMN',
 'IT',
 'GE',
 'GEHC',
 'GEV',
 'GEN',
 'GNRC',
 'GD',
 'GIS',
 'GM',
 'GPC',
 'GILD',
 'GPN',
 'GL',
 'GDDY',
 'GS',
 'HAL',
 'HIG',
 'HAS',
 'HCA',
 'DOC',
 'HSIC',
 'HSY',
 'HES',
 'HPE',
 'HLT',
 'HOLX',
 'HD',
 'HON',
 'HRL',
 'HST',
 'HWM',
 'HPQ',
 'HUBB',
 'HUM',
 'HBAN',
 'HII',
 'IBM',
 'IEX',
 'IDXX',
 'ITW',
 'INCY',
 'IR',
 'PODD',
 'INTC',
 'ICE',
 'IFF',
 'IP',
 'IPG',
 'INTU',
 'ISRG',
 'IVZ',
 'INVH',
 'IQV',
 'IRM',
 'JBHT',
 'JBL',
 'JKHY',
 'J',
 'JNJ',
 'JCI',
 'JPM',
 'JNPR',
 'K',
 'KVUE',
 'KDP',
 'KEY',
 'KEYS',
 'KMB',
 'KIM',
 'KMI',
 'KKR',
 'KLAC',
 'KHC',
 'KR',
 'LHX',
 'LH',
 'LRCX',
 'LW',
 'LVS',
 'LDOS',
 'LEN',
 'LLY',
 'LIN',
 'LYV',
 'LKQ',
 'LMT',
 'L',
 'LOW',
 'LULU',
 'LYB',
 'MTB',
 'MRO',
 'MPC',
 'MKTX',
 'MAR',
 'MMC',
 'MLM',
 'MAS',
 'MA',
 'MTCH',
 'MKC',
 'MCD',
 'MCK',
 'MDT',
 'MRK',
 'META',
 'MET',
 'MTD',
 'MGM',
 'MCHP',
 'MU',
 'MSFT',
 'MAA',
 'MRNA',
 'MHK',
 'MOH',
 'TAP',
 'MDLZ',
 'MPWR',
 'MNST',
 'MCO',
 'MS',
 'MOS',
 'MSI',
 'MSCI',
 'NDAQ',
 'NTAP',
 'NFLX',
 'NEM',
 'NWSA',
 'NWS',
 'NEE',
 'NKE',
 'NI',
 'NDSN',
 'NSC',
 'NTRS',
 'NOC',
 'NCLH',
 'NRG',
 'NUE',
 'NVDA',
 'NVR',
 'NXPI',
 'ORLY',
 'OXY',
 'ODFL',
 'OMC',
 'ON',
 'OKE',
 'ORCL',
 'OTIS',
 'PCAR',
 'PKG',
 'PANW',
 'PARA',
 'PH',
 'PAYX',
 'PAYC',
 'PYPL',
 'PNR',
 'PEP',
 'PFE',
 'PCG',
 'PM',
 'PSX',
 'PNW',
 'PNC',
 'POOL',
 'PPG',
 'PPL',
 'PFG',
 'PG',
 'PGR',
 'PLD',
 'PRU',
 'PEG',
 'PTC',
 'PSA',
 'PHM',
 'QRVO',
 'PWR',
 'QCOM',
 'DGX',
 'RL',
 'RJF',
 'RTX',
 'O',
 'REG',
 'REGN',
 'RF',
 'RSG',
 'RMD',
 'RVTY',
 'ROK',
 'ROL',
 'ROP',
 'ROST',
 'RCL',
 'SPGI',
 'CRM',
 'SBAC',
 'SLB',
 'STX',
 'SRE',
 'NOW',
 'SHW',
 'SPG',
 'SWKS',
 'SJM',
 'SW',
 'SNA',
 'SOLV',
 'SO',
 'LUV',
 'SWK',
 'SBUX',
 'STT',
 'STLD',
 'STE',
 'SYK',
 'SMCI',
 'SYF',
 'SNPS',
 'SYY',
 'TMUS',
 'TROW',
 'TTWO',
 'TPR',
 'TRGP',
 'TGT',
 'TEL',
 'TDY',
 'TFX',
 'TER',
 'TSLA',
 'TXN',
 'TXT',
 'TMO',
 'TJX',
 'TSCO',
 'TT',
 'TDG',
 'TRV',
 'TRMB',
 'TFC',
 'TYL',
 'TSN',
 'USB',
 'UBER',
 'UDR',
 'ULTA',
 'UNP',
 'UAL',
 'UPS',
 'URI',
 'UNH',
 'UHS',
 'VLO',
 'VTR',
 'VLTO',
 'VRSN',
 'VRSK',
 'VZ',
 'VRTX',
 'VTRS',
 'VICI',
 'V',
 'VST',
 'VMC',
 'WRB',
 'GWW',
 'WAB',
 'WBA',
 'WMT',
 'DIS',
 'WBD',
 'WM',
 'WAT',
 'WEC',
 'WFC',
 'WELL',
 'WST',
 'WDC',
 'WY',
 'WMB',
 'WTW',
 'WYNN',
 'XEL',
 'XYL',
 'YUM',
 'ZBRA',
 'ZBH',
 'ZTS']

In [19]:
### get stocks data
stock_data = yf.download(symbols, start="2000-01-01", end="2024-01-01", group_by="ticker")
stock_data

[******                13%%                      ]  64 of 503 completed

$BF.B: possibly delisted; No price data found  (1d 2000-01-01 -> 2024-01-01)

[*********************100%%**********************]  503 of 503 completed

5 Failed downloads:
['BRK.B']: YFTzMissingError('$%ticker%: possibly delisted; No timezone found')
['SW', 'SOLV', 'GEV']: YFChartError("%ticker%: Data doesn't exist for startDate = 946702800, endDate = 1704085200")
['BF.B']: YFPricesMissingError('$%ticker%: possibly delisted; No price data found  (1d 2000-01-01 -> 2024-01-01)')

Ticker            TSLA                                                  \
Price             Open        High         Low       Close   Adj Close
Date
2000-01-03         NaN         NaN         NaN         NaN         NaN
2000-01-04         NaN         NaN         NaN         NaN         NaN
2000-01-05         NaN         NaN         NaN         NaN         NaN
2000-01-06         NaN         NaN         NaN         NaN         NaN
2000-01-07         NaN         NaN         NaN         NaN         NaN
...                ...         ...         ...         ...         ...
2023-12-22  256.760010  258.220001  251.369995  252.539993  252.539993
2023-12-26  254.490005  257.970001  252.910004  256.609985  256.609985
2023-12-27  258.350006  263.339996  257.519989  261.440002  261.440002
2023-12-28  263.660004  265.130005  252.710007  253.179993  253.179993
2023-12-29  255.100006  255.190002  247.429993  248.479996  248.479996

Ticker                         IPG                                   ...  \
Price            Volume       Open       High        Low      Close  ...
Date                                                                 ...
2000-01-03          NaN  57.687500  57.687500  53.562500  54.312500  ...
2000-01-04          NaN  54.000000  54.000000  49.750000  50.000000  ...
2000-01-05          NaN  49.937500  49.937500  48.125000  48.875000  ...
2000-01-06          NaN  49.000000  50.062500  47.875000  49.000000  ...
2000-01-07          NaN  49.500000  50.875000  48.875000  50.750000  ...
...                 ...        ...        ...        ...        ...  ...
2023-12-22   93249800.0  33.110001  33.130001  32.669998  32.860001  ...
2023-12-26   86892400.0  33.009998  33.230000  32.750000  33.110001  ...
2023-12-27  106494400.0  33.049999  33.189999  32.830002  32.950001  ...
2023-12-28  113619900.0  32.919998  33.070000  32.779999  32.939999  ...
2023-12-29  100615300.0  32.939999  32.950001  32.349998  32.639999  ...

Ticker             ON                                         OKE             \
Price             Low      Close  Adj Close     Volume       Open       High
Date
2000-01-03        NaN        NaN        NaN        NaN   5.526615   5.526615
2000-01-04        NaN        NaN        NaN        NaN   5.403498   5.471896
2000-01-05        NaN        NaN        NaN        NaN   5.403498   5.444537
2000-01-06        NaN        NaN        NaN        NaN   5.430857   5.499256
2000-01-07        NaN        NaN        NaN        NaN   5.444537   5.622373
...               ...        ...        ...        ...        ...        ...
2023-12-22  82.989998  84.010002  84.010002  2431900.0  70.000000  70.489998
2023-12-26  84.150002  85.470001  85.470001  3223600.0  70.500000  71.290001
2023-12-27  84.599998  85.050003  85.050003  3440700.0  70.830002  71.440002
2023-12-28  84.260002  84.980003  84.980003  3063800.0  70.809998  71.190002
2023-12-29  82.889999  83.529999  83.529999  4192400.0  70.709999  70.709999

Ticker
Price             Low      Close  Adj Close   Volume
Date
2000-01-03   5.389818   5.430857   1.707169   921527
2000-01-04   5.335099   5.362458   1.685668   403425
2000-01-05   5.362458   5.417177   1.702868  1007877
2000-01-06   5.376138   5.417177   1.702868   570643
2000-01-07   5.444537   5.622373   1.767371   468759
...               ...        ...        ...      ...
2023-12-22  69.760002  70.160004  67.521019  2226200
2023-12-26  70.190002  71.139999  68.464142  1971100
2023-12-27  70.570000  70.980003  68.310165  1819000
2023-12-28  70.279999  70.519997  67.867470  1654000
2023-12-29  70.139999  70.220001  67.578758  2244900

[6037 rows x 3018 columns]

In [51]:
### get only the adjusted close prices
### get only the adj close prices
adj_close_values = []

for stock in symbols:
    adj_close_values.append(stock_data[stock]['Adj Close'])

adj_close_values = pd.DataFrame(adj_close_values).T
adj_close_values.columns = symbols
adj_close_values.drop(columns=['BRK.B', 'SW', 'SOLV', 'GEV', 'BF.B'], inplace=True)
adj_close_values

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WY,WMB,WTW,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
Date,,,,,,,,,,,,,,,,,,,,,
2000-01-03,19.920647,2.322239,8.327240,NaN,NaN,16.274673,15.500000,25.111118,6.845793,43.532223,...,11.427910,9.267177,NaN,NaN,6.907624,NaN,4.657410,25.027779,NaN,NaN
2000-01-04,19.129103,2.288778,8.089325,NaN,NaN,14.909398,14.625000,24.115332,6.664132,40.206852,...,10.998597,9.061650,NaN,NaN,7.066683,NaN,4.563795,24.666668,NaN,NaN
2000-01-05,19.683195,2.282083,8.074450,NaN,NaN,15.204175,15.000000,24.375113,6.625886,37.712811,...,11.581242,9.622169,NaN,NaN,7.339354,NaN,4.587199,25.138889,NaN,NaN
2000-01-06,21.266287,2.248622,8.356976,NaN,NaN,15.328292,16.000000,24.569931,6.759742,36.276840,...,12.122992,9.827692,NaN,NaN,7.271187,NaN,4.548191,23.777779,NaN,NaN
2000-01-07,21.688448,2.342316,8.446203,NaN,NaN,16.072983,16.250000,25.046181,6.893596,39.299911,...,11.724344,10.089262,NaN,NaN,7.271187,NaN,4.446775,23.513889,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-22,86.848938,80.792915,107.400558,150.669540,350.262146,598.750000,139.600006,18.540096,80.091515,138.850662,...,33.787457,34.285332,237.684372,89.679131,60.272720,112.019325,128.720108,269.410004,119.827827,193.525330
2023-12-26,88.302818,80.911537,107.597565,150.358353,349.254150,598.260010,143.410004,18.792475,80.357018,139.089432,...,34.052952,34.265820,236.694397,90.254379,60.457241,112.993927,128.977539,275.500000,120.923340,194.041458
2023-12-27,88.817398,81.217987,108.149193,150.611191,349.639587,596.080017,146.070007,18.714821,80.543846,139.099396,...,34.180786,34.178009,236.902298,89.887413,60.271160,113.749733,129.551819,275.790009,120.634521,195.431000
2023-12-28,89.593346,81.297058,108.750084,150.484787,347.435944,595.520020,148.759995,18.782766,80.740509,139.049637,...,34.515121,34.080441,237.756683,91.008163,60.613945,113.690063,129.234985,275.350006,121.132477,195.689072
2023-12-29,89.291122,81.494774,108.425011,150.698730,346.763977,596.599976,147.410004,18.685698,81.124001,138.547363,...,34.190620,33.982876,239.624405,90.363480,60.633530,113.729851,129.373611,273.329987,121.202187,195.897491

In [69]:
### substitute nan values with 0
# adj_close_values.fillna(method='bfi', inplace=True)
adj_close_values.bfill(inplace=True)

## rename index name
adj_close_values.index.name = 'Ticker'
adj_close_values

,MMM,AOS,ABT,ABBV,ACN,ADBE,AMD,AES,AFL,A,...,WY,WMB,WTW,WYNN,XEL,XYL,YUM,ZBRA,ZBH,ZTS
Ticker,,,,,,,,,,,,,,,,,,,,,
2000-01-03,19.920647,2.322239,8.327240,21.801893,10.798530,16.274673,15.500000,25.111118,6.845793,43.532223,...,11.427910,9.267177,27.056822,7.065085,6.907624,20.410267,4.657410,25.027779,26.016663,28.477207
2000-01-04,19.129103,2.288778,8.089325,21.801893,10.798530,14.909398,14.625000,24.115332,6.664132,40.206852,...,10.998597,9.061650,27.056822,7.065085,7.066683,20.410267,4.563795,24.666668,26.016663,28.477207
2000-01-05,19.683195,2.282083,8.074450,21.801893,10.798530,15.204175,15.000000,24.375113,6.625886,37.712811,...,11.581242,9.622169,27.056822,7.065085,7.339354,20.410267,4.587199,25.138889,26.016663,28.477207
2000-01-06,21.266287,2.248622,8.356976,21.801893,10.798530,15.328292,16.000000,24.569931,6.759742,36.276840,...,12.122992,9.827692,27.056822,7.065085,7.271187,20.410267,4.548191,23.777779,26.016663,28.477207
2000-01-07,21.688448,2.342316,8.446203,21.801893,10.798530,16.072983,16.250000,25.046181,6.893596,39.299911,...,11.724344,10.089262,27.056822,7.065085,7.271187,20.410267,4.446775,23.513889,26.016663,28.477207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-22,86.848938,80.792915,107.400558,150.669540,350.262146,598.750000,139.600006,18.540096,80.091515,138.850662,...,33.787457,34.285332,237.684372,89.679131,60.272720,112.019325,128.720108,269.410004,119.827827,193.525330
2023-12-26,88.302818,80.911537,107.597565,150.358353,349.254150,598.260010,143.410004,18.792475,80.357018,139.089432,...,34.052952,34.265820,236.694397,90.254379,60.457241,112.993927,128.977539,275.500000,120.923340,194.041458
2023-12-27,88.817398,81.217987,108.149193,150.611191,349.639587,596.080017,146.070007,18.714821,80.543846,139.099396,...,34.180786,34.178009,236.902298,89.887413,60.271160,113.749733,129.551819,275.790009,120.634521,195.431000
2023-12-28,89.593346,81.297058,108.750084,150.484787,347.435944,595.520020,148.759995,18.782766,80.740509,139.049637,...,34.515121,34.080441,237.756683,91.008163,60.613945,113.690063,129.234985,275.350006,121.132477,195.689072
2023-12-29,89.291122,81.494774,108.425011,150.698730,346.763977,596.599976,147.410004,18.685698,81.124001,138.547363,...,34.190620,33.982876,239.624405,90.363480,60.633530,113.729851,129.373611,273.329987,121.202187,195.897491

In [70]:
### save the data
adj_close_values.to_csv("./data/sp_stocks.csv")

## seprate data per period

In [71]:
### pre-pandemic data
adj_close_values.index = pd.to_datetime(adj_close_values.index)
pre_pandemic_data = adj_close_values[adj_close_values.index.year < 2020]
pre_pandemic_data.to_csv("./data/sp_stocks_pre_pandemic.csv")

In [72]:
index_data = pd.read_csv("./data/sp500.csv", index_col=0)
index_data.index = pd.to_datetime(index_data.index)
pre_pandemic_index = index_data[index_data.index.year < 2020]
pre_pandemic_index.to_csv("./data/sp500_index_pre_pandemic.csv")

In [73]:
### only 2019
pre_pandemic_data_2019 = adj_close_values[adj_close_values.index.year == 2019]
pre_pandemic_data_2019.to_csv("./data/sp_stocks_2019.csv")

In [74]:
### pandemic data
pandemic_data = adj_close_values[adj_close_values.index.year >= 2020]
pandemic_data = pandemic_data[pandemic_data.index.year < 2022]
pandemic_data.to_csv("./data/sp_stocks_pandemic.csv")

In [75]:
pandemic_index = index_data[index_data.index.year >= 2020]
pandemic_index = pandemic_index[pandemic_index.index.year < 2022]
pandemic_index.to_csv("./data/sp500_index_pandemic.csv")

In [76]:
### only 2021
pandemic_data_2021 = adj_close_values[adj_close_values.index.year == 2021]
pandemic_data_2021.to_csv("./data/sp_stocks_2021.csv")

In [77]:
### post-pandemic data
post_pandemic_data = adj_close_values[adj_close_values.index.year > 2021]
post_pandemic_data.to_csv("./data/sp_stocks_post_pandemic.csv")

In [78]:
post_pandemic_index = index_data[index_data.index.year > 2021]
post_pandemic_index.to_csv("./data/sp500_index_post_pandemic.csv")

In [79]:
### only 2023
post_pandemic_data_2023 = adj_close_values[adj_close_values.index.year == 2023]
post_pandemic_data_2023.to_csv("./data/sp_stocks_2023.csv")